---
apiVersion: v1
kind: Namespace
metadata:
  name: dashboard
---
apiVersion: v1
kind: Service
metadata:
  name: meter-dev-foo
  namespace: dashboard
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: meter-dev-foo-mapping
      host: dev-foo-dashboard.k736.net
      prefix: /api/meter
      service: meter-dev-foo.dashboard.svc.cluster.local
spec:
  selector:
    app: meter-dev-foo
  ports:
    - port: 80
      targetPort: http-api
  type: ClusterIP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: meter-dev-foo
  namespace: dashboard
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: meter-dev-foo
    spec:
      containers:
      - name: meter-dev-foo
        env:
         - name: BUILD_PROFILE
           value: dev-foo
        image: registry.hub.docker.com/richarddli/meter:7df5535730a7a3b2cb027650d5dc2d55de1a05ea.git
        imagePullPolicy: Always
        resources:
          requests:
            memory: 0.1G
            cpu: 0.1
          limits:
            memory: 0.25G
            cpu: 0.25
        ports:
        - name: http-api
          containerPort: 8080