---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ service.namespace }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ build.name }}
  namespace: {{ service.namespace }}
  {%- if "endpoint" in build.profile %}
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: {{build.name}}-mapping
      host: {{build.profile.host}}
      prefix: {{build.profile.endpoint}}
      service: {{build.name}}.{{service.namespace}}.svc.cluster.local
      {%- if "weight" in build.profile %}
      weight: {{build.profile.weight}}
      {%- endif %}
{% endif %}
spec:
  type: ClusterIP
  selector:
    app: {{ build.name }}
  ports:
    - targetPort: http-api
      port: 80
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ build.name }}
  namespace: {{ service.namespace }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ build.name }}
    spec:
      containers:
        - name: {{build.name}}
          image: {{ build.images["Dockerfile"] }}
          env:
            - name: BUILD_PROFILE
              value: {{build.profile.name}}
          ports:
            - name: http-api
              containerPort: 8080
